### ISSUE TITLE
ambiguous genitalia

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3511]
consider adding terms for 
ambiguous genitalia
ambiguous male genitalia
ambiguous female genitalia

Questions:
Should this be limited to external genitalia?
Do we need male and female or is just the parent enough?

See J:15425, J:98554, J:66817 for possible relevant existing annotations

See Ambiguous genitalia HP:0000062

**Comment by anna-anagnostop** [comment]
Add new term:
ambiguous external genitalia under abnormal reproductive system morphology (look at HP:0000062 definition and use sex instead of gender)
DEF: an external genital phenotype that is not clearly assignable to a single sex
SYN: indeterminate external genitalia
SYN: ambiguous genitalia (broad synonym)

Add child terms:

ambiguous male external genitalia (child of ambiguous external genitalia and abnormal external male genitalia morphology MP:0009199)
DEF: ambiguous external genitalia in an organism with XY genetic sex
SYN: ambiguous external genitalia in males

ambiguous female external genitalia (child of ambiguous external genitalia and abnormal external female genitalia morphology MP:0003126)
DEF: ambiguous external genitalia in an organism with XX genetic sex
SYN: ambiguous external genitalia in females

**Comment by anna-anagnostop** [comment]
Added new terms:
ambiguous external genitalia MP:0031377
ambiguous male external genitalia MP:0031378
ambiguous female external genitalia MP:0031379
