### ISSUE TITLE
abnormal mouth morphology

### ISSUE THREAD

**Issue by sbello** [mgijax/mammalian-phenotype-ontology#3790]
the definition of abnormal mouth morphology is "any structural anomaly of the oral cavity" but there is a child term abnormal oral cavity morphology with the definition "any structural anomaly of the anatomical cavity at the start of the digestive tract that is enclosed by the mouth" so we need to revise the definition of abnormal mouth morphology

relates to CHARGE syndrome 'Narrow mouth'

We may also want to add terms for abnormal mouth size as there are annotations for wider or gaping mouths

**Comment by anna-anagnostop** [comment]
UBERON term for mouth [UBERON:0000165](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000165)
DEF: The proximal portion of the digestive tract, containing the oral cavity and bounded by the oral opening. In vertebrates, this extends to the pharynx and includes gums, lips, tongue and parts of the palate. Typically also includes the teeth, except where these occur elsewhere (e.g. pharyngeal jaws) or protrude from the mouth (tusks).

UBERON has additional child term oral opening [UBERON:0000166](https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FUBERON_0000166)
DEF: The orifice that connects the mouth to the exterior of the body.
EXACT SYNONYMS: mouth | oral fissure | oral orifice | oral part of face

**Comment by anna-anagnostop** [comment]
Existing MP terms:

- macrostomia MP:0009881 
DEF: excessive width of the mouth

- microstomia MP:0009880 
DEF: abnormally decreased size of the mouth

See definitions from Elements of Morphology https://elementsofmorphology.nih.gov/index.cgi?lid=bb5901c8ede2415e

Mouth, Narrow](https://elementsofmorphology.nih.gov/index.cgi?tid=dbaf4cd806daeacb) 
Subjective DEF: apparently decreased width of the oral aperture 
Comments: 
The width of the mouth varies with facial movement and must be assessed when the subject has a relaxed (neutral) face. This term replaces microstomia, small oral aperture, and small mouth because the reduced opening of the mouth is secondary to reduced width. 

Mouth, Wide
Subjective DEF: apparently increased width of the oral aperture 
Comments: 
The width of the mouth varies with facial movement and must be assessed when the subject has a relaxed (neutral) face. This term replaces macrostomia, large mouth, and large oral aperture because these terms imply a wide **and open** mouth. The term should not be used to describe a patient with a lateral oral cleft. 
Annotations: MGI:5707269 (widened oral opening)

**Comment by anna-anagnostop** [comment]
Add new MP term:
open mouth (WHERE DOES THIS BELONG?)

See Open mouth [HP:0000194](https://www.ebi.ac.uk/ols4/ontologies/maxo/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FHP_0000194)
HPO DEF: A facial appearance characterized by a permanently or nearly permanently opened mouth
Annotations: MGI:5700512 (E10.5 embryos exhibit an open mouth); MGI:5510810 (gaping mouth)

**Comment by anna-anagnostop** [comment]
Check definitions, annotations and EQs for:

- absent mouth MP:0000453 

CURRENT DEF: absence of the oral cavity
EQ uses: 'has part' some (absent and ('characteristic of' some (mouth and ('part of' some head))) and ('has modifier' some abnormal))

- oral atresia MP:0009576 

CURRENT DEF: congenital blockage, fusion, or absence of the normal opening of the oral cavity
EQ uses:'has part' some  (atretic and ('characteristic of' some mouth) and ('has modifier' some abnormal))

**Comment by anna-anagnostop** [comment]
Move abnormal oral mucosa morphology directly under abnormal mouth morphology
