### ISSUE TITLE
no equivalent for HP:0030794 and children

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#3837]
Under HP:0010876 Abnormal circulating protein concentration HPO has 
_HP:0030794 Abnormal circulating C-peptide concentration
HP:0030796 Increased C-peptide level
HP:0030795 Reduced C-peptide level_

MPO does not. Suggest to add it.

Used in PMID:34390703

**Comment by anna-anagnostop** [comment]
Annotations from [J:334013](https://www.informatics.jax.org/reference/J:334013), [J:323838](https://www.informatics.jax.org/reference/J:323838), [J:99786](https://www.informatics.jax.org/reference/J:99786), [J:256501](https://www.informatics.jax.org/reference/J:256501),[J:221943](https://www.informatics.jax.org/reference/J:221943)

**Comment by anna-anagnostop** [comment]
abnormal circulating C-peptide level (a child of abnormal circulating protein level MP:0005416)
DEF: anomaly in the amount in the blood of the connecting (C) peptide that links the A and B chains in proinsulin, thereby providing a means to promote their efficient folding and assembly in the endoplasmic reticulum during insulin biosynthesis; after cleavage of proinsulin, C-peptide is stored with insulin in the soluble phase of the secretory granules and is subsequently released in equimolar amounts with insulin, providing an independent indicator of insulin secretion
SYN: abnormal circulating connecting peptide level (exact syn)
SYN: abnormal blood connecting peptide level (exact syn)
SYN: abnormal blood C-peptide level (exact syn)
SYN: abnormal serum C-peptide level (narrow syn)
SYN: abnormal plasma C-peptide level (narrow syn)
SOURCE: PMID:30252282, HP:0030794

decreased circulating C-peptide level 
DEF: a reduction in the concentration of the C-peptide in the blood; since C-peptide is secreted in equimolar amounts to insulin, this feature correlates with reduced insulin secretion

increased circulating C-peptide level 
DEF: an elevation in the concentration of the C-peptide in the blood; since C-peptide is secreted in equimolar amounts to insulin, this feature correlates with increased insulin secretion

**Comment by anna-anagnostop** [comment]
Added new terms:
abnormal circulating C-peptide level MP:0031512
decreased circulating C-peptide level MP:0031513
increased circulating C-peptide level MP:0031514
