### ISSUE TITLE
new term request: myocardial noncompaction

### ISSUE THREAD

**Issue by LaurensWilming** [mgijax/mammalian-phenotype-ontology#4010]
>1. Preferred term label 
A: myocardial noncompaction
B: ventricular myocardial noncompaction
C: atrial myocardial noncompaction

>3. Textual definition 
A: failure of the heart myocardium to reorganize from spongy to solid
B: failure of the heart ventricular myocardium to reorganize from spongy to solid
C: failure of the heart atrial myocardium to reorganize from spongy to solid

>4. Any additional notes to clarify the meaning or use of the term. 
PMID:38951485 J:350502
https://en.wikipedia.org/wiki/Noncompaction_cardiomyopathy

>5. Suggested parent term 
A: MP:0002189 abnormal myocardial trabeculae morphology
A: MP:0010633 myocardium hypertrophy

B: MP:%%%%%%% myocardial noncompaction
B: MP:0010499 abnormal ventricle myocardium morphology

C: MP:%%%%%%% myocardial noncompaction
C: MP:0010581 abnormal atrium myocardial trabeculae morphology

**Comment by sbello** [comment]
Looking at https://www.ahajournals.org/doi/10.1161/01.CIR.0000132478.60674.D0?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200pubmed

compaction is described as "Gradual “compaction” of this spongy meshwork of fibers and intertrabecular recesses, or “sinusoids,” occurs between weeks 5 and 8 of embryonic life," (in humans) 
noncompaction as - The abnormal compaction process in these cases is not fully understood, but pressure overload or myocardial ischemia preventing regression of the embryonic myocardial sinusoids has been suggested. This process results in the persistence of deep intertrabecular recesses in communication with both the ventricular cavity and the coronary circulation.

HPO has terms for noncompaction cardiomyopathy (HP:0012817)
Definition: A type of cardiomyopathy characterized anatomically by deep trabeculations in the ventricular wall, which define recesses communicating with the main ventricular chamber. 

PMID: 34206037
"embryonic spongy pattern of the left ventricle"
“persistence of isolated myocardial sinusoids”, assuming the anomalous LV morphology was due to a developmental defect in regression of the embryonal sinusoids."
Cause may not be a defect in the developmental process "Eventually, recent observations suggest, that LV noncompaction (LVNC) may not be the result of an arrest in the compaction process, but instead results from the compacted myocardium of the ventricular wall, growing into the ventricular lumen in a trabecular fashion "

**Comment by sbello** [comment]
myocardial hypertrabeculation - MP:0014518
myocardial ventricular hypertrabeculation - MP:0014519
myocardial atrial hypertrabeculation - MP:0014520
